name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:   
  build-artifact:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/classpaddev/hollyhock-3:v2.1.1
      credentials:
       username: ${{ github.actor }}
       password: ${{ secrets.github_token }}

    steps:
    - run: apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends python3 python-is-python3 && apt-get install -y --reinstall ca-certificates
    - uses: actions/checkout@v4
      with:
        submodules: true
    - run: make -j
    - uses: actions/upload-artifact@v4
      with:
        path: dist/**
